[package]
name = "in_rust_we_plus_tcpip"
version = "1.0.1"
edition = "2021"

[dependencies]
log = "0.4.21"
log4rs = "1.3.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
